version: '3'

services: 

  laravel:
    build: 
      context: ./
      dockerfile: Dockerfile.prod
    image: carlosmendesrv/laravel:prod
    container_name: laravel
    networks: 
      - laranet

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: carlosmendesrv/nginx:prod
    container_name: nginx
    volumes:
      - .:/var/www/html
    networks: 
      - laranet
    ports: 
      - "8080:80"

networks: 
  laranet:
    driver: bridge      